"""SQLAlchemy models for exams and related entities."""

import enum
import json
from typing import Any

from sqlalchemy import Boolean, Enum, ForeignKey, Integer, String, Text, TypeDecorator
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

# Constants
DEFAULT_PASSING_SCORE = 60
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash-lite"


class JSONText(TypeDecorator):
    """Custom type decorator for JSON stored as TEXT in SQLite.
    
    Automatically serializes dict/list to JSON string when saving,
    and deserializes JSON string to dict/list when loading.
    """

    impl = Text
    cache_ok = True

    def process_bind_param(self, value: Any, dialect: Any) -> str | None:
        """Convert Python object to JSON string for database storage."""
        if value is None:
            return None
        return json.dumps(value, ensure_ascii=False)

    def process_result_value(self, value: str | None, dialect: Any) -> Any:
        """Convert JSON string from database to Python object."""
        if value is None:
            return None
        return json.loads(value)


class ExamType(str, enum.Enum):
    """Exam type enumeration."""

    SQL_TESTING = "sql_testing"
    SQL_ONLY = "sql_only"
    TESTING_ONLY = "testing_only"


class Exam(Base, TimestampMixin):
    """Model for exams table.
    
    Represents an exam with SQL and/or Testing sections, generated by AI
    or created manually by admins.
    """

    __tablename__ = "exams"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    exam_type: Mapped[ExamType] = mapped_column(
        Enum(ExamType, name="exam_type"),
        nullable=False,
        default=ExamType.SQL_TESTING,
    )
    subject: Mapped[str | None] = mapped_column(String, nullable=True)
    
    # Foreign key to users table
    created_by: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    
    duration: Mapped[int] = mapped_column(Integer, nullable=False)  # minutes
    passing_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=DEFAULT_PASSING_SCORE,
    )
    
    # JSON field for exam content (sql_part, testing_part)
    exam_data_json: Mapped[dict[str, Any]] = mapped_column(
        JSONText,
        nullable=False,
    )
    
    # AI generation metadata
    ai_generated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    gemini_model: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default=DEFAULT_GEMINI_MODEL,
    )
    
    # Settings JSON for exam configuration
    settings_json: Mapped[dict[str, Any] | None] = mapped_column(
        JSONText,
        nullable=True,
    )
    
    # Publication status
    is_published: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    
    # Relationships
    creator: Mapped["User"] = relationship("User", back_populates="exams")
